### ISSUE TITLE
Add Template Variables

### ISSUE THREAD

**Issue by korgon** [searchspring/snapfu#76]
In order to support things like `themes` without having a separate template per theme, Snapfu will need to support template variables. These variables should live in a new file, maybe a yaml file named`.snapfu`? Yaml is good for ability to add comments.

```
template:
  name:
  variables:
    - name:
      type:
      description:
      prompt:
      default:

    - name:
      type:
      description:
      prompt:
      default:

```
